/****************************************************************************
 * Copyright (C) 2009-2015 EPAM Systems
 * 
 * This file is part of Indigo ELN.
 * 
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 3 as published by the Free Software
 * Foundation and appearing in the file LICENSE.GPL included in the
 * packaging of this file.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ***************************************************************************/
/*
 * Generated by XDoclet - Do not edit!
 */
package com.chemistry.enotebook.registration.interfaces;

import com.chemistry.enotebook.compoundregistration.classes.RegistrationDetailsVO;
import com.chemistry.enotebook.compoundregistration.exceptions.RegistrationRuntimeException;
import com.chemistry.enotebook.domain.ProductBatchModel;
import com.chemistry.enotebook.registration.ScreenInfoRequest;
import com.chemistry.enotebook.registration.ScreenSearchVO;
import com.chemistry.enotebook.vcr.auxiliary.StatusInfo;
import com.chemistry.enotebook.vnv.exceptions.VnvRuntimeException;

import java.util.List;
import java.util.Map;

public interface RegistrationServiceRemote {

	public java.lang.String executeVnV(java.lang.String molfile,
			java.lang.String stereoisomerCode)
			throws com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public com.chemistry.enotebook.compoundregistration.classes.CompoundRegistrationJobStatus[] getRegisterJobStatus(
			java.lang.String[] jobids)
			throws com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public boolean checkCompoundRegistrationHealth() throws Exception;

	public java.lang.String getRegistrationNoFromBatch(java.lang.String batchNo)
			throws com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public java.util.List<ScreenInfoRequest> getInfoForScreens(
			java.util.List<ScreenInfoRequest> screenInfoRequests)
			throws com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public java.util.List<ScreenSearchVO> searchForScreens(
			com.chemistry.enotebook.registration.ScreenSearchParams params)
			throws com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public com.chemistry.enotebook.vnv.classes.UniquenessCheckVO checkUniqueness(
			java.lang.String molfile, java.lang.String stereoisomerCode,
			boolean includeLegacy)
			throws VnvRuntimeException,
			com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException,
			com.chemistry.enotebook.LoadServiceException;

	public boolean checkUniquenessHealth() throws Exception;

	public com.chemistry.enotebook.compoundmanagement.classes.BarcodeValidationVO validateBarcode(
			com.chemistry.enotebook.compoundmanagement.classes.BarcodeValidationVO barcodeVO)
			throws com.chemistry.enotebook.compoundregistration.exceptions.RegistrationRuntimeException,
			com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public Map<String, RegistrationDetailsVO> getRegistrationInformation(
			java.lang.String[] NBBatchNos)
			throws com.chemistry.enotebook.compoundregistration.exceptions.RegistrationRuntimeException,
			com.chemistry.enotebook.registration.RegistrationTokenInvalidException,
			com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public com.chemistry.enotebook.compoundregistration.classes.CompoundRegistrationStatus[] getRegisterCompoundStatus(
			java.lang.String jobid, java.lang.String plateid, int[] offsets,
			boolean includeStruct)
			throws com.chemistry.enotebook.registration.RegistrationSvcUnavailableException;

	public StatusInfo registerVirtualCompound(String molfile, boolean isDryrun,
			String loaderId) throws RegistrationRuntimeException;

	public long submitBatchesForRegistration(List<ProductBatchModel> batches)
			throws RegistrationRuntimeException;
}
