/****************************************************************************
 * Copyright (C) 2009-2015 EPAM Systems
 * 
 * This file is part of Indigo ELN.
 * 
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 3 as published by the Free Software
 * Foundation and appearing in the file LICENSE.GPL included in the
 * packaging of this file.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ***************************************************************************/
package com.chemistry.enotebook.client.gui.page.batch;

import com.chemistry.enotebook.domain.BatchVnVInfoModel;
import com.chemistry.enotebook.utils.CeNDialog;
import com.chemistry.viewer.ChemistryViewer;
import com.jgoodies.forms.builder.PanelBuilder;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import javax.swing.*;
import java.awt.*;

/**
 *
 * 
 */

class BatchVnVResultViewer extends CeNDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2362691115094206145L;

	private static final Log log = LogFactory
			.getLog(BatchVnVResultViewer.class);

	BatchVnVInfoModel vnvResult = null;
	boolean OK_PRESSED = false;

	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private ChemistryViewer chemistryCanvas = null;

	/** Creates new form BatchVnVResultViewer3 */
	public BatchVnVResultViewer(JFrame parent, BatchVnVInfoModel vnvResult) {

		super(parent, true);
		this.vnvResult = vnvResult;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("Stereoisomer Codes:");

		if (this.vnvResult.getSuggestedSICList().size() > 0) {
			jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
					this.vnvResult.getSuggestedSICList().toArray()));
		} else {
			jComboBox1
					.setModel(new javax.swing.DefaultComboBoxModel(
							new String[] { this.vnvResult
									.getAssignedStereoIsomerCode() }));
		}
		jComboBox1
				.setSelectedItem(this.vnvResult.getAssignedStereoIsomerCode());
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("VnV Status:");
		jLabel3.setText(this.vnvResult.getStatus());
		if (this.vnvResult.isPassed()) {
			jLabel3.setForeground(Color.BLUE);
		} else {
			jLabel3.setForeground(Color.RED);
		}
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("Message From VnV:");
		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 11));
		jTextArea1.setRows(5);
		jTextArea1.setText(this.vnvResult.getErrorMsg());
		jTextArea1.setEditable(false);
		jScrollPane1.setViewportView(jTextArea1);

		try {
			chemistryCanvas = new ChemistryViewer("VnV Result Mol", "");
			chemistryCanvas
					.setChemistry(this.vnvResult.getMolData().getBytes());// chimeProSwing.getMolfileData().getBytes());
		} catch (Exception e) {
			log.error(
					"Failed to initialize the Chemistry Viewer. No structure will appear in dialog.",
					e);
		}

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		this.getContentPane().setLayout(new BorderLayout());
		this.getContentPane().add(this.getPanel());

		pack();

	}// </editor-fold>//GEN-END:initComponents

	private Component getPanel() {
		FormLayout formLayout = new FormLayout(
				"40dlu, 40dlu, 10dlu, 40dlu, 40dlu, 15dlu, 40dlu, 60dlu,13dlu",
				"13dlu, 15dlu, 3dlu, 15dlu, 3dlu, 15dlu, 3dlu, 35dlu, 10dlu, 15dlu, 10dlu, 5dlu");
		PanelBuilder builder = new PanelBuilder(formLayout);
		CellConstraints cc1 = new CellConstraints();
		builder.add(jLabel1, cc1.xyw(1, 2, 2));
		builder.add(jComboBox1, cc1.xyw(4, 2, 2));
		builder.add(chemistryCanvas, cc1.xywh(7, 2, 2, 7));

		builder.add(jLabel2, cc1.xyw(1, 4, 2));
		builder.add(jLabel3, cc1.xyw(4, 4, 2));

		builder.add(jLabel4, cc1.xyw(1, 6, 2));

		builder.add(jScrollPane1, cc1.xyw(2, 8, 4));

		builder.add(jButton1, cc1.xy(5, 10));
		builder.add(jButton2, cc1.xy(7, 10));

		return builder.getPanel();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		this.vnvResult.setAssignedStereoIsomerCode((String) this.jComboBox1
				.getSelectedItem());
		OK_PRESSED = true;
		this.dispose();
		// TODO add your handling code here:

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		OK_PRESSED = false;
		this.dispose();

	}// GEN-LAST:event_jButton2ActionPerformed

}
