/****************************************************************************
 * Copyright (C) 2009-2015 EPAM Systems
 * 
 * This file is part of Indigo ELN.
 * 
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 3 as published by the Free Software
 * Foundation and appearing in the file LICENSE.GPL included in the
 * packaging of this file.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ***************************************************************************/
/*
 * Generated by XDoclet - Do not edit!
 */
package com.chemistry.enotebook.chloracnegen.interfaces;

import com.chemistry.enotebook.chloracnegen.classes.Structure;
import com.chemistry.enotebook.chloracnegen.delegate.ChloracnegenDelegateException;
import com.chemistry.enotebook.session.security.SessionIdentifier;

public interface ChloracnegenService {
	public Structure checkChloracnegen(Structure struct, SessionIdentifier sessionID ) throws ChloracnegenDelegateException;
}
