LOAD DATA
INFILE *
INTO TABLE INDIGO_OWNER.CEN_PROPERTIES
FIELDS TERMINATED BY ',' 
(
    SITE_CODE,
    ENABLED_FLAG,
    XML_METADATA_FILE FILLER char,
    REAGENT_PROPS_FILE FILLER char,
    XML_METADATA LOBFILE(XML_METADATA_FILE) TERMINATED BY EOF,
    REAGENT_DB_PROPERTIES LOBFILE(REAGENT_PROPS_FILE) TERMINATED BY EOF
)
BEGINDATA
GBL,YES,xml\xml_metadata.xml,xml\reagent_db_properties.xml
SITE1,YES,xml\xml_metadata_site.xml,xml\reagent_db_properties_site.xml
