/****************************************************************************
 * Copyright (C) 2009-2015 EPAM Systems
 * 
 * This file is part of Indigo ELN.
 * 
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 3 as published by the Free Software
 * Foundation and appearing in the file LICENSE.GPL included in the
 * packaging of this file.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ***************************************************************************/
/*
 * Generated by XDoclet - Do not edit!
 */
package com.chemistry.enotebook.session.security;


/**
 * Data object 
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * 
 * @version ${version}
 */
public class UserData extends java.lang.Object implements java.io.Serializable {

	static private final long serialVersionUID = 275562540305065210L;	/* begin value object */

	private String userName;
	private String fullUserName;
	private String siteCode;
	private boolean validUser;
	private String xmlMetaData;
	private String auditLog;
	private String myReagentList;
	/**
	 * @param userName
	 * @param xmlMetaData
	 * @param auditLog
	 * @param myReagent
	 */
	public UserData(String userName, 
					String fullUserName,	
					String siteCode,
					boolean validUser,
					String xmlMetaData, 
					String auditLog,
					String myReagentList) {
		this.userName = userName;
		this.fullUserName = fullUserName;
		this.siteCode = siteCode;
		this.validUser = validUser;
		this.xmlMetaData = xmlMetaData;
		this.auditLog = auditLog;
		this.myReagentList = myReagentList;
	}
	/* end value object */

	public UserData() {
	}

	public UserData(UserData otherData) {

	}

	public String toString() {
		StringBuffer str = new StringBuffer("{");

		str.append("\nNt User :").append(userName).append("\nXml Meta data :")
				.append(xmlMetaData).append("\nAudit Log :").append(auditLog);
		str.append('}');

		return (str.toString());
	}

	public boolean equals(Object pOther) {
		if (pOther instanceof UserData) {
//			UserData lTest = (UserData) pOther;
			boolean lEquals = true;

			return lEquals;
		} else {
			return false;
		}
	}

	public int hashCode() {
		int result = 17;

		return result;
	}

	/**
	 * @return Returns the auditLog.
	 */
	public String getAuditLogReason() {
		return auditLog;
	}
	/**
	 * @param auditLog
	 *            The auditLog to set.
	 *  
	 */
	public void setAuditLogReason(String auditLog) {
		if (auditLog != null && auditLog.length() > 0) 
		    if (this.auditLog != null && this.auditLog.length() > 0)
			    this.auditLog = this.auditLog + "; " + auditLog;
		    else 
			    this.auditLog = auditLog;
	}
	
	/**
	 * @return Returns the myReagent.
	 */
	public String getMyReagentsList() {
		return myReagentList;
	}
	/**
	 * @param myReagent
	 *            The myReagent to set.
	 */
	public void setMyReagentsList(String myReagentList) {
		this.myReagentList = myReagentList;
	}
	
	/**
	 * @return Returns the userName.
	 */
	public String getUserName() {
		return userName;
	}
	/**
	 * @param userName
	 *            The userName to set.
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	/**
	 * @return Returns the xmlMetaData.
	 */
	public String getXmlMetaData() {
		return xmlMetaData;
	}
	/**
	 * @param xmlMetaData
	 *            The xmlMetaData to set.
	 */
	public void setXmlMetaData(String xmlMetaData) {
		this.xmlMetaData = xmlMetaData;
	}
	
	/**
	 * @return Returns the fullUserName.
	 */
	public String getFullUserName() {
		return fullUserName;
	}
	/**
	 * @param fullUserName The fullUserName to set.
	 */
	public void setFullUserName(String fullUserName) {
		this.fullUserName = fullUserName;
	}
	
	/**
	 * @return Returns the siteCode.
	 */
	public String getSiteCode() {
		return siteCode;
	}
	/**
	 * @param siteCode The siteCode to set.
	 */
	public void setSiteCode(String siteCode) {
		this.siteCode = siteCode;
	}
	
	/**
	 * @return Returns the validUser.
	 */
	public boolean isValidUser() {
		return validUser;
	}
	/**
	 * @param validUser The validUser to set.
	 */
	public void setValidUser(boolean validUser) {
		this.validUser = validUser;
	}

	public String getFirstNameFromFullName() {
		String firstName = "";
		String[] results = fullUserName.split(" ");
		if (results.length > 0) {
			String middleInit = "";
			if (results.length > 1) firstName = results[1];
			if (results.length > 2) middleInit = results[2];
			if (firstName.length() == 1 && middleInit.length() > 1) 
				firstName = middleInit;
		}
		return firstName;
	}
	
	public String getLastNameFromFullName() {
		String lastName = "";
		String[] results = fullUserName.split(" ");
		if (results.length > 0)
			lastName = results[0].substring(0, results[0].length() - 1 );
		return lastName;
	}
}