/****************************************************************************
 * Copyright (C) 2009-2015 EPAM Systems
 * 
 * This file is part of Indigo ELN.
 * 
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 3 as published by the Free Software
 * Foundation and appearing in the file LICENSE.GPL included in the
 * packaging of this file.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ***************************************************************************/
/*
 * Generated by XDoclet - Do not edit!
 */
package com.chemistry.enotebook.sessiontoken.interfaces;

import com.chemistry.enotebook.sessiontoken.delegate.SessionTokenAccessException;

public interface SessionTokenRemote {

	public void createSessionInfo(String sessionToken, String uid) throws SessionTokenAccessException;
	
	public boolean findSessionInfo(String sessionToken) throws SessionTokenAccessException;
	
	public void deleteSessionInfo(String sessionToken)  throws SessionTokenAccessException;
}
